name: Update Notion Cache

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC daily
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-cache:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv

    - name: Create update_cache.py
      run: |
        cat > update_cache.py << 'EOL'
        import os
        import json
        import time
        import requests
        from pathlib import Path

        # Direct values since they're public
        NOTION_TOKEN = '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'
        SUBJECT_DATABASE_ID = '2674b67cbdf84a11a057a29cc24c524f'
        PHARMACOLOGY_DATABASE_ID = '9ff96451736d43909d49e3b9d60971f8'
        ETG_DATABASE_ID = '22282971487f4f559dce199476709b03'
        ROTATION_DATABASE_ID = '69b3e7fdce1548438b26849466d7c18e'

        class NotionCache:
            def __init__(self):
                self.cache_dir = Path("cache")
                self.cache_dir.mkdir(exist_ok=True)

            def update_cache(self, database_id: str):
                """Fetch and save all pages from a Notion database to the cache"""
                headers = {
                    "Authorization": f"Bearer {NOTION_TOKEN}",
                    "Notion-Version": "2022-06-28",
                    "Content-Type": "application/json"
                }
                pages = []
                has_more = True
                start_cursor = None

                while has_more:
                    payload = {
                        "filter": {
                            "property": "For Search",
                            "checkbox": {
                                "equals": True
                            }
                        },
                        "page_size": 100
                    }
                    if start_cursor:
                        payload["start_cursor"] = start_cursor

                    try:
                        response = requests.post(
                            f"https://api.notion.com/v1/databases/{database_id}/query",
                            headers=headers,
                            json=payload
                        )
                        response.raise_for_status()
                        data = response.json()
                        pages.extend(data['results'])
                        has_more = data.get('has_more', False)
                        start_cursor = data.get('next_cursor')
                    except Exception as e:
                        print(f"Error fetching from Notion: {e}")
                        break

                cache_path = self.cache_dir / f"{database_id}.json"
                try:
                    with cache_path.open('w', encoding='utf-8') as f:
                        json.dump({
                            'version': 1,
                            'timestamp': time.time(),
                            'pages': pages
                        }, f)
                    print(f"Saved {len(pages)} pages to cache for database {database_id}")
                except Exception as e:
                    print(f"Error saving cache: {e}")

        def update_notion_cache():
            """Update all Notion database caches"""
            notion_cache = NotionCache()
            notion_cache.update_cache(SUBJECT_DATABASE_ID)
            notion_cache.update_cache(PHARMACOLOGY_DATABASE_ID)
            notion_cache.update_cache(ETG_DATABASE_ID)
            notion_cache.update_cache(ROTATION_DATABASE_ID)

        if __name__ == "__main__":
            update_notion_cache()
        EOL

    - name: Update cache
      run: python update_cache.py

    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add cache/
        git commit -m "Update cache" -a || exit 0
        git push
